name: HelloWorld
author: jaguth
description: An Example of how to create a simple Spigot plugin
version: 1.0
main: com.jaguth.spigotpluggin.helloworld.HelloWorldPluggin
commands:
  echo:
    description: Echos a message to everyone
    usage: "Usage: /echo <your message>"